## 8문제   (지난편 12문제)     OX

In [13]:
def plusF(bbb, *args):     # 일반 매개변수, 가변 매개변수-인자값 무한개    / 가변, 키워드 매개변수가 뒤에 와야 한다.
    print(args[1]+args[2])

In [14]:
plusF('안녕',3,4,5,6)

9


In [ ]:
## Beautiful Soup  <-- 정답
### pandas 자료구조가 아닌 것은?                              Series(vector), DataFrame(matrix), Panal(3D), ???
### numpy 데이터 구조 파악. 튜플로                            shape
#(주관식) np.arange(3,12).reshape(3,3) 출력(print)하면?       
# [[ 3  4  5]
# [ 6  7  8]
# [ 9 10 11]]
# 컴마 없다.   
### arr=np.arange(3,12).reshape(3,3)                          np.sum(arr) 출력하면?                   총합
### print(np.sum(arr, axis=0))                                매 행에서, 같은 열을 더한다.  axis=0 밑으로, axis=1 오른쪽으로 합

In [8]:
import numpy as np

arr=np.arange(3,12).reshape(3,3)
print(arr)
print('\n', np.sum(arr, axis=0))
arr

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [18 21 24]


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
'''
pandas

loc, iloc
iat, at

dropna()
fillna()         직접 값을 지정할 때?           fillna( value=5  )          default?    value=0  ,   axis=0
inplace=True
'''

12
21
30


In [ ]:
# for 문 안나온단다..