## 배열 생성

In [ ]:
'''
수학관련분야 통계연산시 사용되는 파이썬의 라이브러리
1) array()
2) random()
'''

In [7]:
import numpy as np

myList = [4,5,6,7]
print(myList,type(myList))

myArr = np.array(myList)
print(myArr, type(myArr), '\t<--- 출력 결과물!') # nd = n dimension , dnarray는 list 기반
myArr # 이런식으로 출력하는 것은 정식이 아니다. --> print(myArr)
# [4 5 6 7] <--- 이것이 출력 결과이다. 문제 나온다. array([4, 5, 6, 7]) 이거 아니다!!!!

[4, 5, 6, 7] <class 'list'>
[4 5 6 7] <class 'numpy.ndarray'> 	<--- 출력 결과물!


array([4, 5, 6, 7])

In [ ]:
'''
리스트와 np.array 차이점
1. 출력 결과가 다르게 나타난다. comma 없다.
2. 리스트 보다 np.array가 빠르고 메모리 효율이 높다.
3. 자료형이 여러개 가능 vs. 한가지만 가능
'''

In [17]:
a = np.random.rand(5)
print(a, type(a))

b = np.random.randint(1,10,10) # 10은 포함 안한다. 중복 가능
print(b)

c = np.random.randn(10) # 가우시안 분포
print(c)

[0.83959437 0.74012586 0.18009267 0.60569015 0.34768209] <class 'numpy.ndarray'>
[7 3 6 2 8 8 5 8 8 2]
[ 0.93160388 -1.92699903  1.09925615  1.34430736 -0.87830932  0.55763882
 -0.44312328 -1.08485655 -0.28109451  0.4074743 ]


## 배열 초기화

In [ ]:
'''
3-9
zeros(), ones(), eye(), full(,), arange(), ...
'''

In [33]:
zeros = np.zeros(10)   # 실수값 0.0 으로 채운다.
print(zeros)

ones = np.ones(10)    # 실수값 1.0 으로 채운다.
print(ones)

print('', np.arange(3), '\n', np.arange(3,7), '\n', np.arange(3,10,2)) # arange(x,y,z)  z = 스텝이다.  (갯수 아니다!  rand는 갯수이다!

'''
np.array에 연산적용 할 수 있다. 모든 원소에 적용한다.
'''
print(np.ones(10)*4)
print(np.zeros(5)+3)

full = np.full((5,5), 7)
print(full)   # INT 값으로 되네?

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0 1 2] 
 [3 4 5 6] 
 [3 5 7 9]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[3. 3. 3. 3. 3.]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [39]:
L = [ 1,2,3, '사만다']
print(L)                 # 다른 형태의 값들이 함게 들어갈 수 있다.

narr = np.array(L)
print(narr, type(narr))              # 같은 형태의 값만 들어갈 수 있다.
narr

[1, 2, 3, '사만다']
['1' '2' '3' '사만다'] <class 'numpy.ndarray'>


array(['1', '2', '3', '사만다'], dtype='<U11')

In [40]:
narr_1 = np.array([1,2,3,4], dtype=np.float)
print(narr_1)

[1. 2. 3. 4.]


## np.array 속성, 함수

In [48]:
arr1 = np.array([[1.0, 2.1, 3],[4,5,6]], dtype = np.int32)
print(arr1, type(arr1))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [52]:
print(np.ndim(arr1))
print(np.shape(arr1))   # shape 결과는 튜플로 나온다.
print(np.size(arr1))
print('-'*20)  # (위) 함수      (밑) 속성
print(arr1.ndim)
print(arr1.shape)   # shape 결과는 튜플로 나온다.
print(arr1.size)

2
(2, 3)
6
--------------------
2
(2, 3)
6


In [60]:
arr2 = np.arange(32)
print(arr2)

print('')
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

print('')
print(arr2.reshape(4,8))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]

1
(32,)
32

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [80]:
arr3 = np.random.randn(4,4)    # 실행할 때마다 값이 변한다.
print(arr3)

np.random.seed(0)     # 시드값을 설정하면 값이 고정된다. 심지어 서로 같은 값을 공유한다.

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


## 인덱싱과 슬라이싱

In [83]:
np.random.seed(0)
arr4 = np.random.randint(10,20,16).reshape(4,4)
print(arr4)

[[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]
 [18 18 11 16]]


In [99]:
'''
(문제)
1. arr4에서 첫번째 줄의 첫 13을 가져오려면?
2. 두번째 줄의 값들을 가져오려면?
3. 전체 행에 대해서 4번재 열을 가지고 오려면?
'''

print(arr4[0, 2]) # print(arr4[0][2])
print(arr4[1,], arr4[1,:], arr4[1], arr4[1,0:], '\t', arr4[1:2,:])
print(arr4[:,3], arr4[0:, 3], '\n', arr4[:,3:4])

13
[17 19 13 15] [17 19 13 15] [17 19 13 15] [17 19 13 15] 	 [[17 19 13 15]]
[13 15 16 16] [13 15 16 16] 
 [[13]
 [15]
 [16]
 [16]]


## 인덱싱과 조건 슬라이싱

In [116]:
print(arr3)
print(arr3>1)

print('')
print((arr3>1)*arr3)
print(arr3[arr3>1])

[[1.76405235 0.40015721 0.97873798 2.2408932 ]
 [1.86755799 0.         0.95008842 0.        ]
 [0.         0.4105985  0.14404357 1.45427351]
 [0.76103773 0.12167502 0.44386323 0.33367433]]
[[ True False False  True]
 [ True False False False]
 [False False False  True]
 [False False False False]]

[[1.76405235 0.         0.         2.2408932 ]
 [1.86755799 0.         0.         0.        ]
 [0.         0.         0.         1.45427351]
 [0.         0.         0.         0.        ]]
[1.76405235 2.2408932  1.86755799 1.45427351]


In [121]:
print(arr3)
arr3[arr3<0] = 0        # 중요하다!!!

[[1.76405235 0.40015721 0.97873798 2.2408932 ]
 [1.86755799 0.         0.95008842 0.        ]
 [0.         0.4105985  0.14404357 1.45427351]
 [0.76103773 0.12167502 0.44386323 0.33367433]]
[[1.76405235 0.40015721 0.97873798 2.2408932 ]
 [1.86755799 0.         0.95008842 0.        ]
 [0.         0.4105985  0.14404357 1.45427351]
 [0.76103773 0.12167502 0.44386323 0.33367433]]


## numpy 통계함수

In [125]:
'''
sum(), max(), min(), cumsum(), argmax()
'''
print(arr4, '\n')

print(np.sum(arr4))
print(np.sum(arr4, axis=0))    # 결과값: 행   
print(np.sum(arr4, axis=1))    # 결과값: 열    즉, 행의 합산을 나타낸다.   15+10+13+13 = 51

[[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]
 [18 18 11 16]] 

237
[62 61 54 60]
[51 64 59 63]
